# Generated by Django 5.2.7 on 2025-11-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='permission_code',
            field=models.CharField(default='guest', max_length=255),
            preserve_default=False,
        ),
    ]
